site_name: Nassim Blog
theme: slate # lux
plugins:
  - search
  - macros
  - include-markdown
  - awesome-pages

nav:
  - Home: "https://www.nassim.com.br/"
  - DLT: categories/DLT/index.md
  - Javascript: categories/Javascript/index.md

  - Software: categories/Software/index.md

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - assets/custom.css
