site_name: Nassim Blog
theme:
  name: material
plugins:
  - search
  - macros
nav:
  - Home: index.md
  - Posts:
      - "DAG-based DLT Concepts": posts/dag-based-dlt-concepts.md

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - assets/custom.css
