site_name: Nassim Blog
theme: material
plugins:
  - search
  - macros
  - include-markdown
  - awesome-pages

nav:
  - Home: index.md
  - Posts:
      - "DAG-based DLT Concepts": posts/dag-based-dlt-concepts.md
  - Categories:
      - DLT: categories/DLT/index.md
      - Software: categories/Software/index.md

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - assets/custom.css
