site_name: Nassim Blog
theme: lux # lux
plugins:
  - search
  - macros
  - include-markdown
  - awesome-pages

nav:
  - Home: "https://www.nassim.com.br/"
  - Categories:
      - Data: categories/Data/index.md
      - DLT: categories/DLT/index.md
      - Software: categories/Software/index.md
  - Disclaimer: "disclaimer.md"
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - assets/custom.css
