site_name: Blog
theme:
  name: material # lux
  palette:
    primary: nassim_primary
    accent: nassim_accent
  logo: assets/imgs/white_logo.png
  favicon: assets/imgs/favicon.png

plugins:
  - search
  - macros
  - include-markdown
  - awesome-pages

nav:
  - Feed: "."
  - Categories:
      - Data: categories/Data/index.md
      - DLT: categories/DLT/index.md
      - Software: categories/Software/index.md
  - Disclaimer: "disclaimer.md"
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - assets/custom.css

extra:
  generator: false
  homepage: https://nassim.com.br
  rss_feed_url: rss.xml # Adding the RSS feed URL to the extra config

