name: Deploy MkDocs Site to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t blog .

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$VPS_IP" >> ~/.ssh/known_hosts
          scp Dockerfile docker-compose.yml requirements.txt root@"$VPS_IP":/app/blog/
          scp -r ./* root@"$VPS_IP":/app/blog/
          ssh root@"$VPS_IP" 'cd /app/blog && docker-compose -f docker-compose.yml up --build -d'
